theme: jekyll-theme-minimal
title: The Linguist
description: "The Linguist is held by Shijie [ʂʅ51 tɕjɛ35] Wang who graduated from Xi'an Jiaotong-Liverpool University with a bachelor’s degree in Applied English (First Class). My main research area is psycholinguistics, and I research the dynamic relationship between language acquisition and individual differences variables such as personality traits, emotions, and digital literacy."
