theme: jekyll-theme-minimal
title: Shijie Wang
description: Shijie [ʂʅ51 tɕjɛ35] Wang, who was graduated from Xi’an Jiaotong-Liverpool University, is interested in Psycholinguistics, Bi/Multilingualism, Individual Difference, and Quantitative Research Method.  Research Gate: https://www.researchgate.net/profile/Shijie_Wang16  ORCID: https://orcid.org/0000-0003-2624-8103"
